[project]
name = "comfyui-studiodeep"
version = "0.1.5"
description = "Custom Nodes for Creative Engineering in ComfyUI at Studio Deep (Freelance Generative AI Engineer)"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "anthropic",
    "openai",
    "requests",
]

[project.urls]
Repository = "https://github.com/studiodeep-ai/comfyui-studiodeep"

[tool.comfy]
PublisherId = "studiodeep"
DisplayName = "StudioDeep"
Icon = ""
